### ISSUE TITLE
Where are the calls to the WM8731 codec?

### ISSUE THREAD

**Issue by tony1tf** [Rhizomatica/sbitx-core#1]
Searched but couldn't find.
Tony

**Comment by rafael2k** [comment]
There are no calls to WM8731. The interface with it is done through ALSA subsystem. This project implements only the control plane, not the data plane.

**Comment by tony1tf** [comment]
Ok, thanks for the clarification. I was starting to look for solutions to
whether the code can run with the standard 12.288MHz xtal in the WM8731.
Sbitx uses 12.000 MHz.

**Comment by rafael2k** [comment]
Hi Tony. I think yes you can. Take a look here:
https://github.com/torvalds/linux/blob/master/sound/soc/codecs/wm8731.c

I need to refresh my head, but if I remember well, you'll need to change the mclk to 12288000 in the device tree file of "audioinjector" (no need to recompile kernel).

**Comment by tony1tf** [comment]
Awesome, thanks!

And the code is in the R Pi linux distro:

https://github.com/raspberrypi/linux/blob/rpi-6.1.y/sound/soc/codecs/wm8731.c

I just have to work out how the clock freq parameter is sent to the driver.

Tony

**Comment by tony1tf** [comment]
Hi Rafael

I'm getting out of my depth again! Apologies that this is off topic.

The only overlay file for the wm8731 in RPi boot/overlays doesn't take
parameters, so I am not sure how they get read by the codec's c code:

Name:   audioinjector-wm8731-audio
Info:   Configures the audioinjector.net audio add on soundcard
Load:   dtoverlay=audioinjector-wm8731-audio
Params: <None>

Tony

**Comment by rafael2k** [comment]
Indeed... I'm not sure too which is the correct way to initialize the values there.
Looking at "audioinjector-wm8731-audio-overlay.dts", nothing there also.
:/

Certainly is not the right place, but the engineers here definitely know where to properly set the mclk:
https://github.com/raspberrypi/linux/issues

**Comment by kk4das** [comment]
From Farhan it is set in the Audio Injector driver....

[https://github.com/Ysurac/raspberry_kernel_mptcp/blob/master/sound/soc/bcm/audioinjector-pi-soundcard.c](url)

Line 43

As I said in the BITX forum I don't know enough about this to know if there is an easy fix or not.

73,
Dean
KK4DAS

**Comment by tony1tf** [comment]
Hi Dean

That driver is interesting as it does indeed have the 12MHz contraint (BTW - your link doesn't link - have to copy and paste). It's not the same as the one in the 'official' RPi linux distribution here:
https://github.com/raspberrypi/linux/blob/rpi-6.1.y/sound/soc/codecs/wm8731.c
As a relative novice in these matters, I don't know how you force the Pi to use a particular bit of code in it's kernel.
Tony

**Comment by rafael2k** [comment]
There is nothing really to fix, we just lack the knowledge on where to change the clock driving the wm8731.
Tony, the idea is to change "bcm2835_rates_12000000" to something like "bcm2835_rates_12288000". Also need to change "bcm2835_constraints_12000000".

https://github.com/raspberrypi/linux/blob/rpi-6.1.y/sound/soc/bcm/audioinjector-pi-soundcard.c

Then re-compile the kernel.

**Comment by tony1tf** [comment]
Hi Rafael

It's the principle of recompiling the kernel that frightens me!

Tony

**Comment by rafael2k** [comment]
It is mostly just like any other C code.
Just changing the module would be enough, so no need to play with the boot files.
https://www.raspberrypi.com/documentation/computers/linux_kernel.html

Go till the "Building the kernel", then run just:
make -j4 modules

And copy over the ".ko", or, for initial testing, just rmmod the snd_soc_audioinjector_pi_soundcard and insmod the newly compiled kernel module with the changes.

It is scary but fun too!
: )
